name: CI_alphafold
on:
  schedule: 
    - cron: "0 16 * * 1,4"
  push:
    branches:
    - main
    - dev
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v4
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ matrix.python-version }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Execute notebook
        env:
          TF_CPP_MIN_LOG_LEVEL: "2"   # hides INFO & WARNING from TF/XLA
          JAX_PLATFORMS: "cpu"        # force CPU backend, avoids CUDA plugin errors
          TF_ENABLE_ONEDNN_OPTS: "0"  # stops oneDNN perf warnings
        run: |
          jupyter nbconvert \
            --to html \
            --execute \
            --ExecutePreprocessor.timeout=-1 \
            --allow-errors \
            test_gget_alphafold.ipynb

      - name: Commit and push new data
        run: |-
          git config user.name "Test gget alphafold"
          git config user.email ""
          git status
          git add test_gget_alphafold.html
          timestamp=$(date -u)
          git commit -m "Latest test: ${timestamp}" || exit 0
          git push

      - name: Clean up
        run: |
          rm test_gget_alphafold.html
