name: CI_alphafold
on:
  schedule: 
    - cron: "0 16 * * 1,4"
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ matrix.python-version }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Execute notebook
        run: jupyter nbconvert --to 'html' --execute test_gget_alphafold.ipynb

      - name: Commit and push new data
        run: |-
          git config user.name "Test gget alphafold"
          git config user.email ""
          git status
          git add test_gget_alphafold.html
          timestamp=$(date -u)
          git commit -m "Latest test: ${timestamp}" || exit 0
          git push

      - name: Clean up
        run: |
          rm test_gget_alphafold.html
